### ISSUE TITLE
Make document title configurable 

### ISSUE THREAD

**Issue by lemol** [kalutheo/elm-ui-explorer#57]
As of https://github.com/kalutheo/elm-ui-explorer/blob/master/src/UIExplorer.elm#L658, the title of the document is hardcoded has "Storybook Elm".

Would you consider the possibility to make it configurable? If so, I will be happy to send a PR.

**Comment by kalutheo** [comment]
Hello totally  agree 😊 PR is most than welcome 
Thanks !

**Comment by lemol** [comment]
Thank you @kalutheo ,

The solution I find is to include the field `title : Maybe String` in `Config` type:

```elm
type alias Config a b c =
    { customModel : a
    , customHeader : Maybe (CustomHeader b)
    , title : Maybe String
    , update : b -> Model a b c -> ( Model a b c, Cmd b )
    , subscriptions : Model a b c -> Sub b
    , viewEnhancer : ViewEnhancer a b c
    , menuViewEnhancer : MenuViewEnhancer a b c
    , onModeChanged : Maybe (ColorMode -> Cmd (Msg b))
    }
```

So that the customization will be:

```elm

    config =
        { defaultConfig
            | title = Just "My custom title"
        }
```

Are you ok with this API change?

**Comment by georgesboris** [comment]
Hello folks – since this discussion happened a while ago and I was looking for the same feature, I created a PR with a proposed change. The only difference between mine and @lemol is that instead of passing a Maybe String, I'm just using a `customTitle` (following the same pattern as other arguments).

```elm
type alias Config a b c =
    {
    ...
    , customTitle : String
    ...
    }
```

The default config is changed so it now says `customTitle = "UI Explorer"` – so it's a non-breaking change and everything will work just fine if someone just uses the default config. Also, there are fewer changes to the codebase since we're not introducing a `Maybe String`.

**Comment by kalutheo** [comment]
Hello, 
The latest version provides a way to customise the title of the explorer :
https://github.com/kalutheo/elm-ui-explorer/releases/tag/9.0.0
An example can be found here : https://github.com/kalutheo/elm-ui-explorer/blob/master/examples/button/ExplorerWithFlags.elm#L24
